### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by AryanAg08** [jiitopticachapter/Optica-Hack-Fest#1]
**Description**: Build an app that fetches and displays weather information based on user input (city).
**Features**: Search bar for entering city names, display temperature and conditions.
**Skills**: API fetching (e.g., OpenWeatherMap), DOM manipulation.

**Comment by Saarthak1234** [comment]
Good evening sir. I'd be happy to contribute if you assign this task to me :)

**Comment by AryanAg08** [comment]
Okk @Saarthak1234 Good luck!!

**Comment by Aryanj33** [comment]
@AryanAg08 hello sir, can you assign this issue to me

**Comment by AryanAg08** [comment]
@Aryanj33 this issue is already assigned !! You can try other issues available!!
