### ISSUE TITLE
Light/Dark Mode Switch

### ISSUE THREAD

**Issue by Geekyash10** [jiitopticachapter/Optica-Hack-Fest#12]
**Description**:
 Build a simple toggle switch that allows users to switch between light and dark modes for the webpage interface.

**Features**:
Toggle button to switch between light mode (default) and dark mode.
Changes the background color, text color, and other key elements when switching modes.

**Skills**:
DOM manipulation to change CSS styles dynamically.
Managing user preferences with local storage.
CSS for theming (defining light and dark mode styles).
Event handling for toggling the mode when the switch is clicked.

**Comment by Aryanj33** [comment]
@Geekyash10 kindly assign me this
