### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by Geekyash10** [jiitopticachapter/Optica-Hack-Fest#13]
**Description**: Build a basic calculator that performs arithmetic operations like addition, subtraction, multiplication, and division.

**Features**:
Input field to display numbers and results.
Number buttons (0-9) for user input.
Operator buttons for addition, subtraction, multiplication, and division.
"Clear" button to reset the input and result.
"Equal" button to evaluate the expression.
Support for keyboard input (optional).

**Skills**:
Html, CSS, JavaScript
Simple error handling (e.g., dividing by zero).

**Comment by AvinashUmrao** [comment]
kindly assign this task .. would be happy to contribute
@Geekyash10

**Comment by Geekyash10** [comment]
okk @AvinashUmrao  Good Luck !
