### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by Geekyash10** [jiitopticachapter/Optica-Hack-Fest#16]
**Description**: Build a simple interactive Tic-Tac-Toe game where two players take turns marking Xs and Os on a 3x3 grid, with the goal of getting three in a row horizontally, vertically, or diagonally.

**Features**:
- 3x3 grid where players can click to place their mark (X or O).
- Player turns alternate between X and O.
- Win detection when a player gets three marks in a row (horizontally, vertically, or diagonally).
- Display a message declaring the winner or a draw if all cells are filled with no winner.
- Option to restart the game.

**Skills**:
- HTML for creating the grid and buttons.
- CSS for styling the grid, marks, and overall layout.
- JavaScript for handling game logic (player turns, win/draw detection).
- DOM manipulation to update the grid with player marks and display the game outcome.

**Comment by vansh1293** [comment]
sir please assign me this issue

**Comment by vansh1293** [comment]
sir can you please assign me this issue

**Comment by Geekyash10** [comment]
ok @vansh1293  Good Luck !

**Comment by vansh1293** [comment]
sir i have completed the assigned task
