### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by AryanAg08** [jiitopticachapter/Optica-Hack-Fest#5]
**Description:** Build a web app that displays a random quote each time a button is clicked.
**Features:** Display area for the quote and author, button to fetch a new quote.
**Skills:** API fetching (e.g., Quotes API), DOM manipulation.

**Comment by damarudhvarma** [comment]
@AryanAg08 can you  assign this issue to me

**Comment by AryanAg08** [comment]
@damarudhvarma can you explain your workflow or the issue!!

**Comment by damarudhvarma** [comment]
- Set up the environment: Choose a front-end framework 
- Fetch quotes: Use an API like <b>Quotable or ZenQuotes</b> to get a random quote using fetch().
- Design the UI: Create an interface with a quote display area, author, and a button for fetching new quotes. I use <b> Aceternity UI, shadcn UI libraries</b>
- Update the DOM: Use JavaScript to insert the quote and author into the UI when a new quote is fetched.
- Enhance the app: Add loading indicators, animations, or sharing features.
- Deploy the app: Deploy using platforms like Netlify or Vercel.


This gives you the structure or workflow I follow for this project

**Comment by Muhammadahmedanis** [comment]
Assign me this issue so i can fix it

**Comment by AryanAg08** [comment]
Sorry guys!! This repository is for Jiit Specific !!

**Comment by ShauryaRahlon** [comment]
Hello sir can u please assign me this issue.
Here is an overview of what I will do
I will use a quotes api like ninja api or any other relevant api to fetch the info in JSON format.
Then I will add some basic features to quotes such as highlighting or storing, etc and add animations using react's inbuilt libraries.

**Comment by AryanAg08** [comment]
Ok @ShauryaRahlon good luck
