### ISSUE TITLE
Task Management App

### ISSUE THREAD

**Issue by AryanAg08** [jiitopticachapter/Optica-Hack-Fest#7]
Description: Create a task management app with features for assigning, completing, and filtering tasks.
Features: User authentication, drag-and-drop functionality for task organization, and filtering options.
Skills: DOM manipulation, event handling, and local storage.

**Comment by jaanayra** [comment]
Hello sir ,I would be grateful if you assign me this task.

**Comment by AryanAg08** [comment]
okk @jaanayra Good Luck!!
